export const InjectionTokens = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  COURSE_REPOSITORY: 'COURSE_REPOSITORY',
  MODULE_REPOSITORY: 'MODULE_REPOSITORY',
  SECTION_REPOSITORY: 'SECTION_REPOSITORY',
  VIDEO_FILE_REPOSITORY: 'VIDEO_FILE_REPOSITORY',
  VIDEO_METADATA_REPOSITORY: 'VIDEO_METADATA_REPOSITORY',
  COURSE_ACCESS_REPOSITORY: 'COURSE_ACCESS_REPOSITORY',
  VIDEO_STORAGE: 'VIDEO_STORAGE',
  PASSWORD_HASHER: 'PASSWORD_HASHER',
  TOKEN_SERVICE: 'TOKEN_SERVICE',
} as const;
